#!/usr/bin/env python3
"""
Output Formatting Module for Land Assembly Calculator
Generates markdown and JSON reports
"""

from datetime import datetime
from zoneinfo import ZoneInfo
from typing import Dict, List
import json


def generate_markdown_report(
    project_name: str,
    phasing_output: str,
    budget_output: str,
    resource_output: str,
    delay_output: str = None,
    metadata: Dict = None
) -> str:
    """
    Generate complete markdown report.

    Args:
        project_name: Project name
        phasing_output: Formatted phasing strategy
        budget_output: Formatted budget analysis
        resource_output: Formatted resource allocation
        delay_output: Formatted delay cost analysis (optional)
        metadata: Additional metadata dict

    Returns:
        Complete markdown report string
    """
    output = []

    # Header
    eastern = ZoneInfo("America/Toronto")
    timestamp = datetime.now(eastern).strftime("%Y-%m-%d %H:%M:%S %Z")

    output.append(f"# Land Assembly Analysis: {project_name}\n")
    output.append(f"**Generated:** {timestamp}\n")

    if metadata:
        output.append("## Project Overview\n")
        if 'project_type' in metadata:
            output.append(f"**Project Type:** {metadata['project_type']}")
        if 'num_parcels' in metadata:
            output.append(f"**Total Parcels:** {metadata['num_parcels']}")
        if 'total_value' in metadata:
            output.append(f"**Total Estimated Value:** ${metadata['total_value']:,.0f}")
        output.append("")

    # Sections
    output.append(phasing_output)
    output.append("\n---\n")
    output.append(budget_output)
    output.append("\n---\n")
    output.append(resource_output)

    if delay_output:
        output.append("\n---\n")
        output.append(delay_output)

    # Footer
    output.append("\n---\n")
    output.append("*Generated by Land Assembly Calculator*\n")
    output.append("*Uses shared land_assembly_utils, timeline_utils, and risk_utils*")

    return '\n'.join(output)


def generate_json_output(
    project_name: str,
    phasing_result: Dict,
    budget_result: Dict,
    resource_result: Dict,
    delay_result: Dict = None,
    input_data: Dict = None
) -> Dict:
    """
    Generate JSON output for programmatic use.

    Args:
        project_name: Project name
        phasing_result: Phasing strategy result
        budget_result: Budget analysis result
        resource_result: Resource allocation result
        delay_result: Delay cost analysis result (optional)
        input_data: Original input data (optional)

    Returns:
        Complete results dictionary
    """
    eastern = ZoneInfo("America/Toronto")
    timestamp = datetime.now(eastern).isoformat()

    output = {
        'metadata': {
            'project_name': project_name,
            'generated_at': timestamp,
            'calculator_version': '1.0.0'
        },
        'phasing_strategy': phasing_result,
        'budget_analysis': budget_result,
        'resource_allocation': resource_result
    }

    if delay_result:
        output['delay_cost_analysis'] = delay_result

    if input_data:
        output['input_parameters'] = input_data

    return output


def save_json_output(data: Dict, output_path: str):
    """
    Save JSON output to file.

    Args:
        data: Dictionary to save
        output_path: Output file path
    """
    with open(output_path, 'w') as f:
        json.dump(data, f, indent=2)


def save_markdown_report(report: str, output_path: str):
    """
    Save markdown report to file.

    Args:
        report: Markdown report string
        output_path: Output file path
    """
    with open(output_path, 'w') as f:
        f.write(report)


def format_summary_table(phasing_result: Dict, budget_result: Dict, resource_result: Dict) -> str:
    """
    Generate executive summary table.

    Args:
        phasing_result: Phasing strategy result
        budget_result: Budget analysis result
        resource_result: Resource allocation result

    Returns:
        Markdown table string
    """
    output = []

    output.append("## Executive Summary\n")
    output.append("| Metric | Value |")
    output.append("|--------|-------|")
    output.append(f"| Total Parcels | {phasing_result['total_parcels']} |")
    output.append(f"| Total Budget | ${budget_result['total_budget']:,.0f} |")
    output.append(f"| Contingency Rate | {budget_result['contingency_rate']:.1f}% |")
    output.append(f"| Estimated Duration | {phasing_result['total_duration_estimate_days']} days ({phasing_result['total_duration_estimate_days'] / 30:.1f} months) |")
    output.append(f"| Professional Services Cost | ${resource_result['total_cost']:,.0f} |")
    output.append(f"| Average Cost per Parcel | ${budget_result['per_parcel_avg']:,.0f} |")

    return '\n'.join(output)


def format_warnings(warnings: List[str]) -> str:
    """
    Format validation warnings.

    Args:
        warnings: List of warning messages

    Returns:
        Formatted markdown string
    """
    if not warnings:
        return ""

    output = []
    output.append("## Warnings\n")
    for warning in warnings:
        output.append(f"- :warning: {warning}")

    return '\n'.join(output)


def get_eastern_timestamp() -> str:
    """
    Get current timestamp in Eastern time.

    Returns:
        Formatted timestamp string (YYYY-MM-DD_HHMMSS)
    """
    eastern = ZoneInfo("America/Toronto")
    return datetime.now(eastern).strftime("%Y-%m-%d_%H%M%S")
